sentence = input()
sentence = sentence.replace(",", "")
sentence = sentence.replace(".", "")
sentence = sentence.replace("!", "")
sentence = sentence.replace("?", "")
sentence = sentence.lower()
print(sentence)
